#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

if (fortified()) {
	echo (new App\Core\Install\Fortify)->handle_install();
	exec('composer dump-autoload');
} else {
	echo "Fortify not detected on your app.";
}
